### PR TITLE
I added a translator function to translate between Arabic and English…

### PR DESCRIPTION
**Pull request by Joshua-Nweze**
…, plus I edited the nav bar moving nav items to the right

### CODE REVIEW

**Comment by zaidalyafeai** [comment]
Thank you @Joshua-Nweze for the PR. We would like to have a human translation, not a machine translation. If you would like I could create a sheet with the translations of each paragraph.

**Comment by Joshua-Nweze** [comment]
Don't you want the translation to made with an API? Do you want to
translate with what you've written already?

**Comment by zaidalyafeai** [comment]
@Joshua-Nweze here is a translation sheet https://docs.google.com/spreadsheets/d/1ntLLMwI_HR8a9jCx7IE-LDCip78DB4scz_dlJlQnQMY/edit?usp=drivesdk

**Comment by zaidalyafeai** [comment]
@Joshua-Nweze here is a translation sheet https://docs.google.com/spreadsheets/d/1ntLLMwI_HR8a9jCx7IE-LDCip78DB4scz_dlJlQnQMY/edit?usp=drivesdk

**Comment by Joshua-Nweze** [comment]
The file you sent has the translation for only the index page, what about talks and publication page?

**Comment by zaidalyafeai** [comment]
Other pages only contain a few words which are translated.

**Comment by Joshua-Nweze** [comment]
Okay, I'll work with that

**Comment by zaidalyafeai** [comment]
That would be awesome, dont forget to set everything right to left btw.

**Comment by Joshua-Nweze** [comment]
Okay, I'm working on that, and i'll soon  b e done

**Pull request closed without merging**
