### PR TITLE
Added translation

### PR DESCRIPTION
**Pull request by Joshua-Nweze**
I added translations in the site for Arabic and English, and I aligned nav items to right. If there is any changes to be made let me know

### CODE REVIEW

**Comment by zaidalyafeai** [comment]
@Joshua-Nweze thank you very much. Can you please resolve the conflicts?

**Comment by Joshua-Nweze** [comment]
Okay done, In the publication page they're some text content there that you didn't give me translations for. Check it out and send translations let me make the changes

**Comment by Joshua-Nweze** [comment]
Okay done, In the publication page they're some text content there that you didn't give me translations for. Check it out and send translations let me make the changes

**Comment by Eaalghamdi** [comment]
@Joshua-Nweze  I added an express server and moved the files around. Can you please check your translation function? 

Thanks

**Comment by Joshua-Nweze** [comment]
okay, i'll do that right away

**Pull request closed without merging**
